# Generated by Django 5.0.7 on 2024-08-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0004_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
