# Generated by Django 5.0.7 on 2024-08-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0005_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
